// One Piece comprehensive data

export interface Character {
  id: string
  name: string
  alias: string
  status: "alive" | "dead"
  occupation: string
  bounty: string
  devilFruit: string
  haki: string[]
  age: number
  image: string
  description: string
  crew?: string
}

export interface Villain {
  id: string
  name: string
  alias: string
  status: "alive" | "dead"
  devilFruit: string
  powers: string[]
  danger: "low" | "medium" | "high" | "extreme"
  image: string
  description: string
  arc: string
}

export interface Location {
  id: string
  name: string
  type: "island" | "sea"
  sea: string
  image: string
  description: string
  notableFacts: string[]
}

export interface AnimeEpisode {
  id: string
  number: number
  title: string
  arc: string
  releaseDate: string
  description: string
}

export interface Movie {
  id: string
  title: string
  year: number
  image: string
  description: string
  boxOffice: string
}

export interface Opening {
  id: string
  number: number
  title: string
  artist: string
  episodes: string
  year: number
}

export interface Ending {
  id: string
  number: number
  title: string
  artist: string
  episodes: string
  year: number
}

export interface Music {
  id: string
  title: string
  type: "opening" | "ending" | "soundtrack" | "insert-song"
  artist: string
  season?: string
  description: string
  year: number
  audioFile: string
}

export interface PirateCrew {
  id: string
  name: string
  captain: string
  members: string[]
  bounty: string
  image: string
  status: "active" | "disbanded"
  description: string
}

// Characters Data
export const characters: Character[] = [
  {
    id: "1",
    name: "Luffy",
    alias: "Monkey D. Luffy",
    status: "alive",
    occupation: "Pirate Captain",
    bounty: "3,000,000,000+",
    devilFruit: "Gomu Gomu no Mi (Human-Human Fruit)",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 19,
    image: "/luffy1.jpg",
    description:
      "Captain of the Straw Hat Pirates. Determined to become King of the Pirates and achieve his dreams. Known for his rubber body and incredible willpower.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "2",
    name: "Zoro",
    alias: "Roronoa Zoro",
    status: "alive",
    occupation: "Swordsman",
    bounty: "1,111,000,000+",
    devilFruit: "None",
    haki: ["Armament Haki", "Observation Haki"],
    age: 21,
    image: "/zoro.jpg",
    description:
      "Master swordsman and vice-captain of Straw Hat Pirates. Wields three swords and has a dream to become the world's greatest swordsman.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "3",
    name: "Nami",
    alias: "Nami",
    status: "alive",
    occupation: "Navigator",
    bounty: "366,000,000+",
    devilFruit: "None",
    haki: ["Observation Haki"],
    age: 20,
    image: "/nami.jpg",
    description:
      "Navigator of the Straw Hat Pirates. Skilled cartographer and weather expert. Dreams of creating a map of the entire world.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "4",
    name: "Ussop",
    alias: "Usopp",
    status: "alive",
    occupation: "Sniper",
    bounty: "500,000,000+",
    devilFruit: "None",
    haki: ["Observation Haki"],
    age: 19,
    image: "/ussop.jpg",
    description:
      "Sniper of the Straw Hat Pirates. Known for his tall tales and creative weapons. Dreams of becoming a brave warrior.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "5",
    name: "Sanji",
    alias: "Vinsmoke Sanji",
    status: "alive",
    occupation: "Cook",
    bounty: "1,032,000,000+",
    devilFruit: "None",
    haki: ["Armament Haki", "Observation Haki"],
    age: 21,
    image: "/sanji.jpg",
    description:
      "Cook of the Straw Hat Pirates. Master martial artist using devastating kick techniques. Dreams of finding All Blue.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "6",
    name: "Chopper",
    alias: "Tony Tony Chopper",
    status: "alive",
    occupation: "Doctor",
    bounty: "1,000,000,000+",
    devilFruit: "Hito Hito no Mi (Human-Human Fruit)",
    haki: ["Armament Haki"],
    age: 17,
    image: "/chopper.jpg",
    description: "Doctor of the Straw Hat Pirates. A reindeer who ate a human fruit. Dreams of curing all diseases.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "7",
    name: "Robin",
    alias: "Nico Robin",
    status: "alive",
    occupation: "Archaeologist",
    bounty: "930,000,000+",
    devilFruit: "Hana Hana no Mi (Flower-Flower Fruit)",
    haki: ["Armament Haki", "Observation Haki"],
    age: 30,
    image: "/robin.jpg",
    description:
      "Archaeologist of the Straw Hat Pirates. Only person who can read Poneglyphs. Dreams of learning the true history.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "8",
    name: "Franky",
    alias: "Cutty Flam",
    status: "alive",
    occupation: "Shipwright",
    bounty: "394,000,000+",
    devilFruit: "None",
    haki: ["Armament Haki"],
    age: 36,
    image: "/franky.jpg",
    description:
      "Shipwright of the Straw Hat Pirates. Cyborg with incredible strength. Dreams of building a ship to sail the world.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "9",
    name: "Brooks",
    alias: "Brook",
    status: "alive",
    occupation: "Musician",
    bounty: "383,000,000+",
    devilFruit: "Yomi Yomi no Mi (Revival-Revival Fruit)",
    haki: ["Armament Haki", "Observation Haki"],
    age: 90,
    image: "/brook.jpg",
    description: "Musician of the Straw Hat Pirates. A skeleton brought back to life. Dreams of reuniting with Laboon.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "10",
    name: "Jinbe",
    alias: "Knight of the Sea",
    status: "alive",
    occupation: "Helmsman",
    bounty: "1,100,000,000",
    devilFruit: "None",
    haki: ["Armament Haki", "Observation Haki"],
    age: 46,
    image: "/jinbe.jpg",
    description:
      "A Fish-Man and former Warlord of the Sea. Calm, honorable, and serves as the helmsman of the Straw Hat Pirates.",
    crew: "Straw Hat Pirates",
  },
  {
    id: "11",
    name: "Shanks",
    alias: "Red-Haired Shanks",
    status: "alive",
    occupation: "Pirate Emperor",
    bounty: "4,948,800,000+",
    devilFruit: "None",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 37,
    image: "/shanks.jpg",
    description:
      "One of the Four Emperors. Inspired young Luffy with dreams of adventure. Powerful swordsman and Haki master.",
    crew: "Red Hair Pirates",
  },
  {
    id: "12",
    name: "Sabo",
    alias: "Chief of Staff of the Revolutionary Army",
    status: "alive",
    occupation: "Revolutionary",
    bounty: "602,000,000",
    devilFruit: "Mera Mera no Mi",
    haki: ["Armament Haki", "Observation Haki"],
    age: 22,
    image: "/sabo.jpg",
    description:
      "Second-in-command of the Revolutionary Army and sworn brother of Luffy and Ace. Inherited Ace’s will and Devil Fruit, fighting for freedom and justice.",
    crew: "Revolutionary Army",
  },
  {
    id: "13",
    name: "Ace",
    alias: "Portgas D. Ace",
    status: "dead",
    occupation: "Pirate Commander",
    bounty: "550,000,000",
    devilFruit: "Mera Mera no Mi",
    haki: ["Armament Haki", "Observation Haki"],
    age: 20,
    image: "/ace.jpg",
    description:
      "Second Division Commander of the Whitebeard Pirates and Luffy’s older brother. Known for his fire abilities and unbreakable loyalty.",
    crew: "Whitebeard Pirates",
  },
  {
    id: "14",
    name: "Whitebeard",
    alias: "Edward Newgate",
    status: "dead",
    occupation: "Pirate Captain",
    bounty: "5,046,000,000",
    devilFruit: "Gura Gura no Mi",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 72,
    image: "/white.jpg",
    description:
      "One of the Four Emperors and the strongest man in the world. Treated his crew as family and stood as a symbol of an era.",
    crew: "Whitebeard Pirates",
  },
  {
    id: "15",
    name: "Vivi",
    alias: "Nefertari Vivi",
    status: "alive",
    occupation: "Princess of Alabasta",
    bounty: "Unknown",
    devilFruit: "None",
    haki: [],
    age: 18,
    image: "/vivi.jpg",
    description:
      "Princess of the Alabasta Kingdom and honorary member of the Straw Hat Pirates. Brave, kind, and deeply devoted to her people.",
    crew: "Alabasta Kingdom",
  },
  {
    id: "16",
    name: "Boa",
    alias: "Boa Hancock",
    status: "alive",
    occupation: "Pirate Empress",
    bounty: "1,659,000,000",
    devilFruit: "Mero Mero no Mi",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 31,
    image: "/boa.jpg",
    description:
      "Captain of the Kuja Pirates and former Warlord of the Sea. Known as the most beautiful woman in the world and deeply in love with Luffy.",
    crew: "Kuja Pirates",
  },
  {
    id: "17",
    name: "Roger",
    alias: "Gol D. Roger",
    status: "dead",
    occupation: "Pirate King",
    bounty: "5,564,800,000",
    devilFruit: "None",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 53,
    image: "/roger.jpg",
    description:
      "The only man to conquer the Grand Line and become King of the Pirates. His execution began the Great Pirate Era.",
    crew: "Roger Pirates",
  },
  {
    id: "18",
    name: "Rayleigh",
    alias: "Silvers Rayleigh",
    status: "alive",
    occupation: "Former First Mate",
    bounty: "Unknown",
    devilFruit: "None",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 78,
    image: "/rayleigh.jpg",
    description:
      "Former first mate of the Roger Pirates, known as the Dark King. Mentor to Luffy in mastering Haki.",
    crew: "Roger Pirates",
  },
  {
    id: "19",
    name: "Shakky",
    alias: "Shakuyaku",
    status: "alive",
    occupation: "Bar Owner",
    bounty: "Unknown",
    devilFruit: "None",
    haki: [],
    age: 64,
    image: "/shakky.jpg",
    description:
      "Owner of Shakky’s Rip-off Bar and former Kuja pirate. Calm, sharp-witted, and closely connected to Rayleigh.",
    crew: "Kuja Pirates (Former)",
  },
  {
    id: "20",
    name: "Vegapunk",
    alias: "Dr. Vegapunk",
    status: "dead",
    occupation: "Scientist",
    bounty: "Unknown",
    devilFruit: "Nomi Nomi no Mi",
    haki: [],
    age: 65,
    image: "/vegapunk.jpg",
    description:
      "The world’s greatest scientist whose intellect surpassed centuries. His research shaped the future of science and warfare.",
    crew: "World Government (Former)",
  },
  {
    id: "21",
    name: "Oden",
    alias: "Kozuki Oden",
    status: "dead",
    occupation: "Samurai / Daimyo",
    bounty: "Unknown",
    devilFruit: "None",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 39,
    image: "/oden.jpg",
    description:
      "Legendary samurai of Wano and former member of both the Whitebeard and Roger Pirates. A free-spirited warrior who opened Wano’s borders.",
    crew: "Kozuki Family",
  },
  {
    id: "22",
    name: "Marco",
    alias: "Marco the Phoenix",
    status: "alive",
    occupation: "Pirate Doctor",
    bounty: "1,374,000,000",
    devilFruit: "Tori Tori no Mi, Model: Phoenix",
    haki: ["Armament Haki", "Observation Haki"],
    age: 45,
    image: "/marco.jpg",
    description:
      "Former First Division Commander of the Whitebeard Pirates. A calm and reliable leader with powerful regenerative abilities.",
    crew: "Whitebeard Pirates",
  },
  {
    id: "23",
    name: "Garp",
    alias: "Monkey D. Garp",
    status: "alive",
    occupation: "Vice Admiral",
    bounty: "None",
    devilFruit: "None",
    haki: ["Armament Haki", "Observation Haki"],
    age: 78,
    image: "/garp.jpg",
    description:
      "Hero of the Marines who cornered Gol D. Roger multiple times. Grandfather of Luffy and Dragon.",
    crew: "Marines",
  },
  {
    id: "24",
    name: "Koby",
    alias: "Hero of Rocky Port",
    status: "alive",
    occupation: "Marine Captain",
    bounty: "None",
    devilFruit: "None",
    haki: ["Observation Haki", "Armament Haki"],
    age: 18,
    image: "/koby.jpg",
    description:
      "A determined Marine officer inspired by Luffy. Rapidly growing in strength and ideals of justice.",
    crew: "Marines",
  },
  {
    id: "25",
    name: "Law",
    alias: "Trafalgar D. Water Law",
    status: "alive",
    occupation: "Pirate Captain / Doctor",
    bounty: "3,000,000,000",
    devilFruit: "Ope Ope no Mi",
    haki: ["Armament Haki", "Observation Haki"],
    age: 26,
    image: "/law.jpg",
    description:
      "Captain of the Heart Pirates and a master strategist. Wielder of the ultimate surgery Devil Fruit.",
    crew: "Heart Pirates",
  }, 
  {
    id: "26",
    name: "Kid",
    alias: "Eustass Kid",
    status: "alive",
    occupation: "Pirate Captain",
    bounty: "3,000,000,000",
    devilFruit: "Jiki Jiki no Mi",
    haki: ["Armament Haki", "Observation Haki", "Conqueror's Haki"],
    age: 23,
    image: "/kid.jpg",
    description:
      "Captain of the Kid Pirates. A violent and fearless pirate with magnetic powers and a rivalry with Luffy.",
    crew: "Kid Pirates",
  },

  {
    id: "27",
    name: "Yamato",
    alias: "Kozuki Oden (Self-Proclaimed)",
    status: "alive",
    occupation: "Warrior",
    bounty: "Unknown",
    devilFruit: "Inu Inu no Mi, Model: Okuchi no Makami",
    haki: ["Conqueror's Haki", "Armament Haki", "Observation Haki"],
    age: 28,
    image: "/yamato.jpg",
    description:
      "Daughter of Kaido who admires Kozuki Oden and fights for Wano’s freedom. Possesses immense strength and will.",
    crew: "Wano Country",
  },  
  {
    id: "28",
    name: "Dragon",
    alias: "Monkey D. Dragon",
    status: "alive",
    occupation: "Leader of the Revolutionary Army",
    bounty: "Unknown",
    devilFruit: "None",
    haki: ["Observation Haki"],
    age: 52,
    image: "/dragon.jpg",
    description:
      "Father of Luffy and the most wanted man in the world. Leads the Revolutionary Army to overthrow corrupt governments and fight for freedom.",
    crew: "Revolutionary Army",
  },
  {
    id: "29",
    name: "Bepo",
    alias: "Bepo",
    status: "alive",
    occupation: "Navigator / Martial Artist",
    devilFruit: "None",
    haki: ["Armament Haki", "Observation Haki"],
    age: 24,
    bounty: "Unknown",
    image: "/bepo.jpg",
    description:
      "A talking polar bear and loyal member of the Heart Pirates. Skilled in martial arts and always supports Law and his crewmates.",
    crew: "Heart Pirates",
  }, 
  {
    id: "30",
    name: "Sengoku",
    alias: "Sengoku the Buddha",
    status: "alive",
    occupation: "Former Fleet Admiral",
    bounty: "Unknown",
    devilFruit: "Hito Hito no Mi, Model: Daibutsu",
    haki: ["Conqueror's Haki", "Armament Haki"],
    age: 80,
    image: "/sengoku.jpg",
    description: "Former Fleet Admiral of the Marines. Wields a Mythical Zoan Devil Fruit that transforms him into a giant Buddha.",
    crew: "Former Marines",
  },
  {
    id: "31",
    name: "Dracule Mihawk",
    alias: "Hawk-Eye Mihawk",
    status: "alive",
    occupation: "World’s Greatest Swordsman",
    bounty: "Unknown",
    devilFruit: "None",
    haki: ["Armament Haki", "Observation Haki"],
    age: 48,
    image: "/mihawk.jpg",
    description: "The strongest swordsman in the world. Travels alone and trains Zoro during his two-year timeskip.",
    crew: "None",
  },
]

// Villains Data
export const villains: Villain[] = [
  {
    id: "v1",
    name: "Blackbeard",
    alias: "Marshall D. Teach",
    status: "alive",
    devilFruit: "Yami Yami no Mi + Gura Gura no Mi",
    powers: ["Dark-Dark Fruit", "Quake-Quake Fruit", "Master Haki"],
    danger: "extreme",
    image: "/blackbeard.jpg",
    description: "One of the Four Emperors. Possesses two Devil Fruits. Major antagonist threatening the entire world.",
    arc: "Post-Timeskip",
  },
  {
    id: "v2",
    name: "Kaido",
    alias: "King of the Beasts",
    status: "dead",
    devilFruit: "Uo Uo no Mi (Fish-Fish Fruit)",
    powers: ["Dragon transformation", "Conqueror's Haki", "Armament Haki"],
    danger: "extreme",
    image: "/kaido.jpg",
    description: "One of the Four Emperors. Nearly indestructible and sought to create a new world order.",
    arc: "Wano",
  },
  {
    id: "v3",
    name: "Doflamingo",
    alias: "Donquixote Doflamingo",
    status: "alive",
    devilFruit: "Ito Ito no Mi (String-String Fruit)",
    powers: ["String manipulation", "Conqueror's Haki", "Armament Haki"],
    danger: "extreme",
    image: "/doflamingo.jpg",
    description: "Former Warlord of the Sea. Creates strings that control everything. Defeated by Luffy in Dressrosa.",
    arc: "Dressrosa",
  },
  {
    id: "v4",
    name: "Crocodile",
    alias: "Crocodile",
    status: "alive",
    devilFruit: "Suna Suna no Mi (Sand-Sand Fruit)",
    powers: ["Sand manipulation", "Armament Haki"],
    danger: "high",
    image: "/crocodile.jpg",
    description: "Former Warlord of the Sea. Controls sand and defeated by Luffy in Alabasta.",
    arc: "Alabasta",
  },
  {
    id: "v5",
    name: "Arlong",
    alias: "Arlong",
    status: "dead",
    devilFruit: "None",
    powers: ["Fish-man abilities", "Sword mastery", "Strong teeth"],
    danger: "high",
    image: "/arlong.jpeg",
    description: "Fishman tyrant who oppressed Nami's village. Killed by Luffy.",
    arc: "East Blue",
  },
  {
    id: "v6",
    name: "Enel",
    alias: "God Enel",
    status: "alive",
    devilFruit: "Goro Goro no Mi (Rumble-Rumble Fruit)",
    powers: ["Electricity manipulation", "Mantra (Observation Haki)", "Speed and flight"],
    danger: "high",
    image: "/enel.jpg",
    description: "Self-proclaimed God of Skypiea. Controls electricity and ruled Skypiea with fear.",
    arc: "Skypiea",
  },
  {
    id: "v7",
    name: "Rob Lucci",
    alias: "Rob Lucci",
    status: "alive",
    devilFruit: "Neko Neko no Mi, Model: Leopard",
    powers: ["Zoan transformation", "Master of Rokushiki techniques", "Observation and Armament Haki"],
    danger: "high",
    image: "/lucci.jpg",
    description: "Top assassin of CP9. Fought Luffy at Enies Lobby and is highly skilled in Rokushiki martial arts.",
    arc: "Enies Lobby",
  },
  {
    id: "v8",
    name: "Caesar Clown",
    alias: "Caesar",
    status: "alive",
    devilFruit: "Gas Gas no Mi",
    powers: ["Gas manipulation", "Chemical weapons", "Scientific genius"],
    danger: "medium",
    image: "/caesar.jpg",
    description: "Mad scientist on Punk Hazard. Creates dangerous chemical weapons and experiments on humans.",
    arc: "Punk Hazard",
  },
  {
    id: "v9",
    name: "Big Mom",
    alias: "Charlotte Linlin",
    status: "alive",
    devilFruit: "Soru Soru no Mi (Soul-Soul Fruit)",
    powers: ["Soul manipulation", "Immense strength", "Armament Haki", "Conqueror's Haki"],
    danger: "extreme",
    image: "/big_mom.jpg",
    description: "One of the Four Emperors. Rules Totto Land with fear and has a huge family army.",
    arc: "Whole Cake Island",
  },
  {
    id: "v10",
    name: "Hody Jones",
    alias: "Hody",
    status: "dead",
    devilFruit: "None",
    powers: ["Fish-man abilities", "Super strength", "Swimming combat skills"],
    danger: "medium",
    image: "/hody.jpg",
    description: "Fish-man extremist who wanted to overthrow humans. Fought Luffy at Fish-Man Island.",
    arc: "Fish-Man Island",
  },
  {
    id: "v11",
    name: "Foxy",
    alias: "Foxy the Silver Fox",
    status: "alive",
    devilFruit: "Noro Noro no Mi",
    powers: ["Slow-Slow Fruit", "Trickery and cunning", "Team tactics"],
    danger: "low",
    image: "/foxy.jpg",
    description: "Pirate who specializes in trickery and games. Fought the Straw Hats in the Davy Back Fight.",
    arc: "Davy Back Fight",
  },
  {
    id: "v12",
    name: "Sugar",
    alias: "Sugar",
    status: "alive",
    devilFruit: "Hobi Hobi no Mi",
    powers: ["Turn people into toys", "Control over memory and obedience", "Stealth manipulation"],
    danger: "high",
    image: "/sugar.jpg",
    description: "Member of the Donquixote Family. Her powers kept Dressrosa under Doflamingo's control.",
    arc: "Dressrosa",
  },
  {
    id: "v13",
    name: "Vergo",
    alias: "Vergo",
    status: "dead",
    devilFruit: "None",
    powers: ["Armament Haki", "Rokushiki techniques", "Extremely strong combat skills"],
    danger: "high",
    image: "/vergo.jpg",
    description: "Corrupt Marine and Doflamingo's right-hand man. Fought against Law and Luffy at Punk Hazard.",
    arc: "Punk Hazard",
  }, 
  {
    id: "v16",
    name: "Buggy",
    alias: "Buggy the Clown",
    status: "alive",
    devilFruit: "Bara Bara no Mi",
    powers: ["Body separation", "Mastery of knife combat", "Trickery and strategy"],
    danger: "medium",
    image: "/buggy.jpg",
    description: "Captain of the Buggy Pirates. Comedic but cunning, with the ability to separate his body into pieces using his Devil Fruit.",
    arc: "Orange Town / Post-Timeskip",
  },
  {
    id: "v17",
    name: "Akainu",
    alias: "Sakazuki",
    status: "alive",
    devilFruit: "Magu Magu no Mi",
    powers: ["Magma manipulation", "Armament Haki", "Observation Haki", "Immense strength and durability"],
    danger: "extreme",
    image: "/akainu.jpg",
    description: "Fleet Admiral of the Marines. Ruthless executor of 'Absolute Justice' and one of the most dangerous individuals in the world.",
    arc: "Post-Marineford / New World",
  },     
]

// Locations Data
export const locations: Location[] = [
  {
    id: "l1",
    name: "Luffy's Village",
    type: "island",
    sea: "East Blue",
    image: "/luffyvillage.jpg",
    description: "The peaceful village where Luffy grew up and first dreamed of becoming a pirate.",
    notableFacts: ["Shanks visited here", "Where Luffy's adventure started", "Quiet farming village"],
  },
  {
    id: "l2",
    name: "Alabasta",
    type: "island",
    sea: "Grand Line",
    image: "/alabasta.jpg",
    description: "A sandy desert kingdom threatened by a great drought. Saved by the Straw Hat Pirates.",
    notableFacts: ["Ruled by Nefertari family", "Major kingdom", "Crocodile's stronghold"],
  },
  {
    id: "l3",
    name: "Wano Country",
    type: "island",
    sea: "New World",
    image: "/wano.jpg",
    description: "An isolated nation of samurai ruled by Kaido. Site of major arc involving Luffy.",
    notableFacts: ["Samurai culture", "Kaido's territory", "Momonosuke is rightful ruler"],
  },
  {
    id: "l4",
    name: "Marineford",
    type: "island",
    sea: "Grand Line",
    image: "/marineford.jpg",
    description: "The headquarters of the World Government's Navy. Site of the Marineford War.",
    notableFacts: ["Navy headquarters", "Whitebeard War location", "Ace's execution"],
  },
  {
    id: "l5",
    name: "Raftel/Laughtale",
    type: "island",
    sea: "New World",
    image: "/laughtale.jpg",
    description: "The legendary final island containing the treasure One Piece. Goal of all pirates.",
    notableFacts: ["Location of One Piece", "Final destination", "Only reached by Pirate King"],
  },
  {
  id: "l6",
  name: "Drum Island",
  type: "island",
  sea: "Grand Line",
  image: "/drum_island.jpg",
  description: "A snowy island known for its medical expertise and the birthplace of Tony Tony Chopper.",
  notableFacts: ["Ruled by Wapol (former)", "Famous for medical care", "Chopper's home"],
},
{
  id: "l7",
  name: "Amazon Lily",
  type: "island",
  sea: "Calm Belt / Grand Line",
  image: "/amazon_lily.jpg",
  description: "An isolated island inhabited only by women, ruled by Boa Hancock and the Kuja Tribe.",
  notableFacts: ["All-female population", "Home of Kuja Tribe", "Hancock's kingdom and palace"],
},
{
  id: "l8",
  name: "Skypiea",
  type: "island",
  sea: "Sky / Grand Line",
  image: "/skypiea.jpg",
  description: "A floating island in the sky with unique culture and history, home to the Shandians and the Sky God Enel.",
  notableFacts: ["Accessible by Knock Up Stream", "Ruled by Enel temporarily", "Sky culture and dials"],
},
{
  id: "l9",
  name: "Enies Lobby",
  type: "island",
  sea: "Grand Line",
  image: "/enies_lobby.jpg",
  description: "The judicial island of the World Government and home to the infamous Gates of Justice.",
  notableFacts: ["Judicial island", "CP9 headquarters", "Connected to Water 7 by sea trains"],
},
{
  id: "l10",
  name: "Thriller Bark",
  type: "island",
  sea: "Grand Line",
  image: "/thriller_bark.jpg",
  description: "A massive haunted ship-island controlled by Gecko Moria, filled with zombies and shadows.",
  notableFacts: ["Largest ship-island", "Home of Gecko Moria", "Haunted by shadows and zombies"],
},
{
  id: "l11",
  name: "Sabaody Archipelago",
  type: "island",
  sea: "Grand Line",
  image: "/sabaody_archipelago.jpg",
  description: "A cluster of mangrove islands near the Red Line, known for the human auctions and Celestial Dragons.",
  notableFacts: ["Home of the Celestial Dragons", "Human auctions", "Bubble-powered islands"],
},
{
  id: "l12",
  name: "Impel Down",
  type: "island",
  sea: "Grand Line / Underwater Prison",
  image: "/impel_down.jpg",
  description: "The infamous underwater prison of the World Government, known for its severe levels and deadly guards.",
  notableFacts: ["Underwater prison", "Led by Magellan", "High-security facility"],
},
{
  id: "l13",
  name: "Fish-Man Island",
  type: "island",
  sea: "Grand Line / Underwater",
  image: "/fishman_island.jpg",
  description: "An underwater paradise home to fish-men and merfolk, located beneath the Red Line.",
  notableFacts: ["Underwater kingdom", "Home to Fish-Man Pirates", "Protected by Neptune and royal family"],
},
{
  id: "l14",
  name: "Punk Hazard",
  type: "island",
  sea: "Grand Line",
  image: "/punk_hazard.jpg",
  description: "A hazardous island split between fire and ice, former laboratory of Caesar Clown.",
  notableFacts: ["Hot and cold regions", "Caesar Clown's lab", "Science experiments conducted"],
},
{
  id: "l15",
  name: "Dressrosa",
  type: "island",
  sea: "Grand Line",
  image: "/dressrosa.jpg",
  description: "A vibrant kingdom ruled by Donquixote Doflamingo, known for its gladiatorial colosseum and toys.",
  notableFacts: ["Ruled by Doflamingo", "Colosseum and toys", "Home of Riku family"],
},
{
  id: "l16",
  name: "Zou",
  type: "island",
  sea: "New World",
  image: "/zou.jpg",
  description: "A giant elephant carrying an entire island on its back, home of the Mink Tribe.",
  notableFacts: ["Giant elephant island", "Mink Tribe home", "Moves slowly across seas"],
},
{
  id: "l17",
  name: "Whole Cake Island",
  type: "island",
  sea: "New World",
  image: "/whole_cake_island.jpg",
  description: "A colorful, candy-themed island ruled by Big Mom, part of Totto Land.",
  notableFacts: ["Ruled by Big Mom", "Candy and cake architecture", "Home of the Charlotte Family"],
},
{
  id: "l18",
  name: "Egghead Island",
  type: "island",
  sea: "New World",
  image: "/egghead_island.jpg",
  description: "A futuristic island known for scientific research and Vegapunk's laboratory.",
  notableFacts: ["Vegapunk's lab", "High-tech facilities", "World Government interest"],
},
{
  id: "l19",
  name: "Elbaf",
  type: "island",
  sea: "New World",
  image: "/elbaf.jpg",
  description: "The legendary island of giants known for its warriors, traditions, and strong sense of honor.",
  notableFacts: ["Island of giants", "Warrior culture", "Strong traditions and festivals"],
},
]

// Media Data
export const animeEpisodes: AnimeEpisode[] = [
  {
    id: "a1",
    number: 1,
    title: "Romance Dawn",
    arc: "East Blue",
    releaseDate: "1999-10-20",
    description: "Luffy begins his journey to become King of the Pirates.",
  },
  {
    id: "a2",
    number: 45,
    title: "The Red-Haired Shanks Appears",
    arc: "Romance Dawn / East Blue",
    releaseDate: "2000-04-10",
    description: "Luffy encounters the pirate Shanks, who inspires him to become a pirate.",
  },
  {
    id: "a3",
    number: 61,
    title: "An Angry Showdown! Cross the Red Line!",
    arc: "Orange Town / East Blue",
    releaseDate: "2000-07-03",
    description: "Luffy and his crew face Buggy the Clown in a major showdown.",
  },
  {
    id: "a4",
    number: 100,
    title: "Defeat the Groggy Monsters",
    arc: "Skypiea",
    releaseDate: "2002-12-22",
    description: "Major battles in the sky island arc.",
  },
  {
    id: "a5",
    number: 130,
    title: "Nami's Courage and the Island of Clouds",
    arc: "Skypiea",
    releaseDate: "2003-01-05",
    description: "The crew reaches Skypiea, and Nami shows her courage against Enel's forces.",
  },
  {
    id: "a6",
    number: 207,
    title: "Enter the Grand Line!",
    arc: "Alabasta",
    releaseDate: "2004-05-09",
    description: "The Straw Hats officially enter the Grand Line and face new challenges.",
  },
  {
    id: "a7",
    number: 312,
    title: "The Death of Portgas D. Ace",
    arc: "Marineford War",
    releaseDate: "2010-07-25",
    description: "Ace dies protecting his brother Luffy during the Marineford War.",
  },
  {
    id: "a8",
    number: 320,
    title: "Whitebeard's End",
    arc: "Marineford War",
    releaseDate: "2011-02-06",
    description: "The death of Whitebeard during the Marineford War.",
  },
  {
    id: "a9",
    number: 516,
    title: "Luffy vs. Doflamingo",
    arc: "Dressrosa",
    releaseDate: "2013-09-29",
    description: "Luffy engages in a fierce battle against Donquixote Doflamingo to liberate Dressrosa.",
  },
  {
    id: "a10",
    number: 574,
    title: "Gear Fourth Awakens",
    arc: "Dressrosa",
    releaseDate: "2014-10-26",
    description: "Luffy unveils his Gear Fourth technique during the fight against Doflamingo.",
  },
  {
    id: "a11",
    number: 629,
    title: "Big Mom Appears",
    arc: "Whole Cake Island",
    releaseDate: "2015-11-08",
    description: "The Straw Hats confront Big Mom for the first time in the Whole Cake Island arc.",
  },
  {
    id: "a12",
    number: 783,
    title: "The Battle Begins! Luffy vs. Katakuri",
    arc: "Whole Cake Island",
    releaseDate: "2017-01-01",
    description: "Luffy fights Charlotte Katakuri in an epic battle to escape Big Mom's territory.",
  },
  {
    id: "a13",
    number: 892,
    title: "Straw Hat Crew Reunited!",
    arc: "Wano Country",
    releaseDate: "2019-05-05",
    description: "The Straw Hats reunite after the two-year timeskip and prepare for the Wano Country battles.",
  },
  {
    id: "a14",
    number: 1000,
    title: "The 1000th Episode",
    arc: "Wano Country",
    releaseDate: "2021-11-14",
    description: "Historic 1000th episode celebration of One Piece anime.",
  },
  {
    id: "a15",
    number: 1048,
    title: "The Final Blow! Luffy vs. Kaido",
    arc: "Wano Country / Post-Wano",
    releaseDate: "2023-02-05",
    description: "Luffy delivers the decisive attack, finally defeating Kaido and ending his reign of terror in Wano.",
  },
  {
    id: "a16",
    number: 1050,
    title: "The Aftermath: New Bounties",
    arc: "Post-Wano",
    releaseDate: "2023-02-19",
    description: "Following the Wano victory, the World Government announces updated bounties for major pirates where luffy becomes the yonko.",
  },
  {
    id: "a17",
    number: 1055,
    title: "Setting Sail for Egghead Island",
    arc: "Egghead",
    releaseDate: "2023-03-26",
    description: "The Straw Hats begin their journey to Egghead Island, home of Dr. Vegapunk and revolutionary technology.",
  },
  {
    id: "a18",
    number: 1058,
    title: "Encountering Vegapunk",
    arc: "Egghead",
    releaseDate: "2023-04-16",
    description: "The crew finally meets Dr. Vegapunk, revealing astonishing advancements in science and secrets of the world.",
  },
  {
    id: "a19",
    number: 1063,
    title: "Egghead Under Siege",
    arc: "Egghead",
    releaseDate: "2023-05-21",
    description: "The island comes under attack by powerful enemies, putting the Straw Hats and Vegapunk in danger.",
  },
];

export const movies: Movie[] = [
  {
    id: "m1",
    title: "One Piece: The Movie",
    year: 2000,
    image: "/one_piece_movie.jpg",
    description: "The Straw Hats' first cinematic adventure, facing the villainous Captain Kuro.",
    boxOffice: "Unknown",
  },
  {
    id: "m2",
    title: "Clockwork Island Adventure",
    year: 2001,
    image: "/clockwork_island.jpg",
    description: "The Straw Hats explore a mysterious island with mechanical traps and face a dangerous villain.",
    boxOffice: "Unknown",
  },
  {
    id: "m3",
    title: "Chopper's Kingdom on the Island of Strange Animals",
    year: 2002,
    image: "/chopper_kingdom.jpg",
    description: "Chopper and the crew face a pirate duo while protecting a mysterious island and its animals.",
    boxOffice: "Unknown",
  },
  {
    id: "m4",
    title: "Dead End Adventure",
    year: 2003,
    image: "/dead_end_adventure.jpg",
    description: "The Straw Hats enter a deadly pirate race filled with traps and rival pirates.",
    boxOffice: "Unknown",
  },
  {
    id: "m5",
    title: "The Cursed Holy Sword",
    year: 2004,
    image: "/cursed_holy_sword.jpg",
    description: "The Straw Hats protect a legendary cursed sword while facing a new enemy pirate crew.",
    boxOffice: "Unknown",
  },
  {
    id: "m6",
    title: "Baron Omatsuri and the Secret Island",
    year: 2005,
    image: "/baron_omatsuri.jpg",
    description: "The crew visits a mysterious island resort and faces deadly trials created by Baron Omatsuri.",
    boxOffice: "Unknown",
  },
  {
    id: "m7",
    title: "Giant Mecha Soldier of Karakuri Castle",
    year: 2006,
    image: "/giant_mecha_soldier.jpg",
    description: "Luffy and crew fight a giant mechanical army to rescue a kidnapped princess.",
    boxOffice: "Unknown",
  },
  {
    id: "m8",
    title: "Episode of Alabasta – The Desert Princess and the Pirates",
    year: 2007,
    image: "/alabasta_movie.jpg",
    description: "Retelling of the Alabasta arc where Luffy confronts Crocodile to save the desert kingdom.",
    boxOffice: "Unknown",
  },
  {
    id: "m9",
    title: "Episode of Chopper Plus – Bloom in Winter, Miracle Sakura",
    year: 2008,
    image: "/chopper_plus.jpg",
    description: "A remake of the Drum Island arc featuring Chopper with new adventures and animation.",
    boxOffice: "Unknown",
  },
  {
    id: "m10",
    title: "One Piece Film: Strong World",
    year: 2009,
    image: "/strong_world.jpg",
    description: "The Straw Hats face the powerful pirate Shiki, who threatens the world with his floating islands.",
    boxOffice: "3.08 Billion Yen",
  },
  {
    id: "m11",
    title: "One Piece 3D: Straw Hat Chase",
    year: 2011,
    image: "/straw_hat_chase.jpg",
    description: "The Straw Hats race against time in a 3D adventure to recover their stolen treasure.",
    boxOffice: "Unknown",
  },
  {
    id: "m12",
    title: "One Piece Film: Z",
    year: 2012,
    image: "/z.jpg",
    description: "Memorable film featuring a former admiral as the main antagonist.",
    boxOffice: "1.6 Billion Yen",
  },
  {
    id: "m13",
    title: "One Piece Film: Gold",
    year: 2016,
    image: "/gold.jpg",
    description: "The crew infiltrates Gran Tesoro, a massive ship-city, and confronts the powerful Gild Tesoro.",
    boxOffice: "5.87 Billion Yen",
  },
  {
    id: "m14",
    title: "One Piece: Stampede",
    year: 2019,
    image: "/stampede.jpg",
    description: "Celebration of One Piece's 20th anniversary with all major characters.",
    boxOffice: "2.6 Billion Yen",
  },
  {
    id: "m15",
    title: "One Piece Film: Red",
    year: 2022,
    image: "/red.jpg",
    description: "Latest One Piece film with stunning animation and new characters.",
    boxOffice: "4.5 Billion+ Yen",
  }
];

export const openings: Opening[] = [
  {
    id: "op1",
    number: 1,
    title: "We Are!",
    artist: "Hiroshi Kitadani",
    episodes: "1-61",
    year: 1999,
  },
  {
    id: "op5",
    number: 5,
    title: "Kaze o Sagashite",
    artist: "Oda Kazumasa",
    episodes: "143-172",
    year: 2002,
  },
  {
    id: "op13",
    number: 13,
    title: "One Day",
    artist: "The Rootless",
    episodes: "457-481",
    year: 2010,
  },
  {
    id: "op25",
    number: 25,
    title: "The Strongest",
    artist: "T-Pablow",
    episodes: "1015+",
    year: 2021,
  },
]

export const endings: Ending[] = [
  {
    id: "ed1",
    number: 1,
    title: "Memories",
    artist: "Taku Takahashi",
    episodes: "1-61",
    year: 1999,
  },
  {
    id: "ed5",
    number: 5,
    title: "Ame Furase",
    artist: "Rie Natsume",
    episodes: "143-172",
    year: 2002,
  },
  {
    id: "ed13",
    number: 13,
    title: "Mirai wa Kyou",
    artist: "Straw Hat Pirates",
    episodes: "457-481",
    year: 2010,
  },
  {
    id: "ed25",
    number: 25,
    title: "Love is a Hurricane",
    artist: "Chara",
    episodes: "1015+",
    year: 2021,
  },
  {
    id: "ed15",
    number: 15,
    title: "Crazy Rainbow",
    artist: "Revo",
    episodes: "555-579",
    year: 2012,
  },
]

export const musicTracks: Music[] = [
  // Iconic Opening Themes
  {
    id: "music1",
    title: "We Are!",
    type: "opening",
    artist: "Hiroshi Kitadani",
    season: "Season 1",
    description: "The iconic first opening theme that launched the series. Energetic and unforgettable.",
    year: 1999,
    audioFile: "/music/openings/we-are.mp3",
  },
  {
    id: "music2",
    title: "Believe",
    type: "opening",
    artist: "Kota Shinzato",
    season: "Early Paradise",
    description: "Powerful opening for the early sailing adventures.",
    year: 2000,
    audioFile: "/music/openings/believe.mp3",
  },
  {
    id: "music3",
    title: "Hikari e",
    type: "opening",
    artist: "The Babystars",
    season: "Skypiea Arc",
    description: "Hopeful and adventurous opening for the sky island arc.",
    year: 2003,
    audioFile: "/music/openings/hikari-e.mp3",
  },
  {
    id: "music4",
    title: "Share the World",
    type: "opening",
    artist: "Kota Shinzato",
    season: "Post-Timeskip",
    description: "Epic opening marking the return after the 2-year timeskip.",
    year: 2009,
    audioFile: "/music/openings/share-the-world.mp3",
  },
  {
    id: "music5",
    title: "The Strongest",
    type: "opening",
    artist: "T-Pablow",
    season: "Current",
    description: "Latest opening theme with modern hip-hop vibes.",
    year: 2021,
    audioFile: "/music/openings/the-strongest.mp3",
  },

  // Iconic Ending Themes
  {
    id: "music6",
    title: "Memories",
    type: "ending",
    artist: "Taku Takahashi",
    season: "Season 1",
    description: "Emotional ending theme reflecting on moments and bonds.",
    year: 1999,
    audioFile: "/music/endings/memories.mp3",
  },
  {
    id: "music8",
    title: "Crazy Rainbow",
    type: "ending",
    artist: "Revo",
    season: "Fishman Island Arc",
    description: "Vibrant and hopeful ending for island paradise arc.",
    year: 2012,
    audioFile: "/music/endings/crazy-rainbow.mp3",
  },

  // Insert Songs & OST
  {
    id: "music9",
    title: "Overtaken",
    type: "insert-song",
    artist: "The Babystars",
    description: "Emotional insert song during intense moments in Thriller Bark arc.",
    year: 2007,
    audioFile: "/music/insert-songs/overtaken.mp3",
  },
  {
    id: "music11",
    title: "Bink's Sake",
    type: "insert-song",
    artist: "Brook",
    description: "Legendary pirate song performed by Brook with incredible emotional weight.",
    year: 2006,
    audioFile: "/music/insert-songs/binks-sake.mp3",
  },
  {
    id: "music12",
    title: "Wa no Kuni",
    type: "soundtrack",
    artist: "Kota Yamaoka",
    season: "Wano Arc",
    description: "Original soundtrack capturing the samurai essence of Wano Country.",
    year: 2020,
    audioFile: "/music/soundtracks/wa-no-kuni.mp3",
  },
]

export const pirateCrew: PirateCrew[] = [
  {
    id: "pc1",
    name: "Straw Hat Pirates",
    captain: "Monkey D. Luffy",
    members: ["Roronoa Zoro", "Nami", "Usopp", "Vinsmoke Sanji", "Tony Tony Chopper", "Nico Robin", "Franky", "Brook"],
    bounty: "7.5 Billion+",
    image: "/strawhats.jpg",
    status: "active",
    description: "The main crew of the series. Started small and became one of the most powerful pirate crews.",
  },
  {
    id: "pc2",
    name: "Red Hair Pirates",
    captain: "Shanks",
    members: ["Shanks", "Ben Beckman", "Yasopp", "Lucky Roux"],
    bounty: "4.948 Billion+",
    image: "/redhair.jpg",
    status: "active",
    description: "One of the Four Emperors. Inspired Luffy to become a pirate.",
  },
  {
    id: "pc3",
    name: "Whitebeard Pirates",
    captain: "Edward Newgate",
    members: ["Portgas D. Ace", "Marco", "Jozu", "Vista"],
    bounty: "5.046 Billion+",
    image: "/whitebeard.jpg",
    status: "disbanded",
    description: "Legendary pirate crew led by Whitebeard. Disbanded after the Marineford War.",
  },
  {
    id: "pc4",
    name: "Heart Pirates",
    captain: "Trafalgar D. Water Law",
    members: ["Trafalgar Law", "Bepo", "Shachi", "Penguin"],
    bounty: "3 Billion+",
    image: "/heart_pirates.jpg",
    status: "active",
    description: "A strategic and well-coordinated crew led by Law. Known for their intelligence and use of the Ope Ope no Mi.",
  },
  {
    id: "pc5",
    name: "Kid Pirates",
    captain: "Eustass Kid",
    members: ["Eustass Kid", "Killer", "Heat", "Wire"],
    bounty: "3 Billion+",
    image: "/kid_pirates.jpg",
    status: "active",
    description: "A ruthless crew led by Kid. Known for their violence, ambition, and rivalry with Luffy.",
  },
  {
    id: "pc6",
    name: "Beast Pirates",
    captain: "Kaido",
    members: ["King", "Queen", "Jack", "All-Stars", "Tobi Roppo"],
    bounty: "Unknown",
    image: "/beast_pirates.jpg",
    status: "active",
    description: "One of the most powerful crews in the world, led by Kaido. Known for Zoan Devil Fruits and immense strength.",
  },
  {
    id: "pc7",
    name: "Big Mom Pirates",
    captain: "Charlotte Linlin",
    members: ["Charlotte Katakuri", "Charlotte Smoothie", "Charlotte Perospero", "Charlotte Cracker"],
    bounty: "Unknown",
    image: "/big_mom_pirates.jpg",
    status: "active",
    description: "Pirates led by Big Mom, one of the Four Emperors. Their family-based crew dominates Totto Land.",
  },
  {
    id: "pc8",
    name: "Roger Pirates",
    captain: "Gol D. Roger",
    members: ["Silvers Rayleigh", "Scopper Gaban", "Banchina"],
    bounty: "Unknown",
    image: "/roger_pirates.jpg",
    status: "disbanded",
    description: "The legendary pirate crew led by the Pirate King. Conquered the Grand Line and found the One Piece.",
  },
  {
    id: "pc9",
    name: "Blackbeard Pirates",
    captain: "Marshall D. Teach",
    members: ["Blackbeard", "Shiliew", "Jesus Burgess", "Van Augur", "Laffitte", "Doc Q", "Vasco Shot"],
    bounty: "Unknown",
    image: "/blackbeard_pirates.jpg",
    status: "active",
    description: "Infamous crew led by Blackbeard. Gained power through Devil Fruits and captured former Whitebeard territories.",
  },
  {
    id: "pc10",
    name: "Kuja Pirates",
    captain: "Boa Hancock",
    members: ["Boa Hancock", "Marigold", "Sandersonia"],
    bounty: "Unknown",
    image: "/kuja_pirates.jpg",
    status: "active",
    description: "All-female crew of Amazon Lily. Renowned for their combat prowess and mastery of Haki.",
  },  
]